# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galbot/singorix_proto/singorix_sensor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from galbot.core_proto import header_pb2 as galbot_dot_core__proto_dot_header__pb2
from galbot.sensor_proto import joint_pb2 as galbot_dot_sensor__proto_dot_joint__pb2
from galbot.sensor_proto import imu_pb2 as galbot_dot_sensor__proto_dot_imu__pb2
from galbot.sensor_proto import effort_pb2 as galbot_dot_sensor__proto_dot_effort__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='galbot/singorix_proto/singorix_sensor.proto',
  package='galbot.singorix_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n+galbot/singorix_proto/singorix_sensor.proto\x12\x15galbot.singorix_proto\x1a\x1egalbot/core_proto/header.proto\x1a\x1fgalbot/sensor_proto/joint.proto\x1a\x1dgalbot/sensor_proto/imu.proto\x1a galbot/sensor_proto/effort.proto\"\xc1\x04\n\x0eSingoriXSensor\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12S\n\x10joint_sensor_map\x18\x02 \x03(\x0b\x32\x39.galbot.singorix_proto.SingoriXSensor.JointSensorMapEntry\x12O\n\x0eimu_sensor_map\x18\x03 \x03(\x0b\x32\x37.galbot.singorix_proto.SingoriXSensor.ImuSensorMapEntry\x12U\n\x11\x65\x66\x66ort_sensor_map\x18\x04 \x03(\x0b\x32:.galbot.singorix_proto.SingoriXSensor.EffortSensorMapEntry\x1aW\n\x13JointSensorMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .galbot.sensor_proto.JointSensor:\x02\x38\x01\x1aS\n\x11ImuSensorMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.galbot.sensor_proto.ImuSensor:\x02\x38\x01\x1aY\n\x14\x45\x66\x66ortSensorMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.galbot.sensor_proto.EffortSensor:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[galbot_dot_core__proto_dot_header__pb2.DESCRIPTOR,galbot_dot_sensor__proto_dot_joint__pb2.DESCRIPTOR,galbot_dot_sensor__proto_dot_imu__pb2.DESCRIPTOR,galbot_dot_sensor__proto_dot_effort__pb2.DESCRIPTOR,])




_SINGORIXSENSOR_JOINTSENSORMAPENTRY = _descriptor.Descriptor(
  name='JointSensorMapEntry',
  full_name='galbot.singorix_proto.SingoriXSensor.JointSensorMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='galbot.singorix_proto.SingoriXSensor.JointSensorMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='galbot.singorix_proto.SingoriXSensor.JointSensorMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=602,
)

_SINGORIXSENSOR_IMUSENSORMAPENTRY = _descriptor.Descriptor(
  name='ImuSensorMapEntry',
  full_name='galbot.singorix_proto.SingoriXSensor.ImuSensorMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='galbot.singorix_proto.SingoriXSensor.ImuSensorMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='galbot.singorix_proto.SingoriXSensor.ImuSensorMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=604,
  serialized_end=687,
)

_SINGORIXSENSOR_EFFORTSENSORMAPENTRY = _descriptor.Descriptor(
  name='EffortSensorMapEntry',
  full_name='galbot.singorix_proto.SingoriXSensor.EffortSensorMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='galbot.singorix_proto.SingoriXSensor.EffortSensorMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='galbot.singorix_proto.SingoriXSensor.EffortSensorMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=689,
  serialized_end=778,
)

_SINGORIXSENSOR = _descriptor.Descriptor(
  name='SingoriXSensor',
  full_name='galbot.singorix_proto.SingoriXSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.singorix_proto.SingoriXSensor.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joint_sensor_map', full_name='galbot.singorix_proto.SingoriXSensor.joint_sensor_map', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imu_sensor_map', full_name='galbot.singorix_proto.SingoriXSensor.imu_sensor_map', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='effort_sensor_map', full_name='galbot.singorix_proto.SingoriXSensor.effort_sensor_map', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SINGORIXSENSOR_JOINTSENSORMAPENTRY, _SINGORIXSENSOR_IMUSENSORMAPENTRY, _SINGORIXSENSOR_EFFORTSENSORMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=778,
)

_SINGORIXSENSOR_JOINTSENSORMAPENTRY.fields_by_name['value'].message_type = galbot_dot_sensor__proto_dot_joint__pb2._JOINTSENSOR
_SINGORIXSENSOR_JOINTSENSORMAPENTRY.containing_type = _SINGORIXSENSOR
_SINGORIXSENSOR_IMUSENSORMAPENTRY.fields_by_name['value'].message_type = galbot_dot_sensor__proto_dot_imu__pb2._IMUSENSOR
_SINGORIXSENSOR_IMUSENSORMAPENTRY.containing_type = _SINGORIXSENSOR
_SINGORIXSENSOR_EFFORTSENSORMAPENTRY.fields_by_name['value'].message_type = galbot_dot_sensor__proto_dot_effort__pb2._EFFORTSENSOR
_SINGORIXSENSOR_EFFORTSENSORMAPENTRY.containing_type = _SINGORIXSENSOR
_SINGORIXSENSOR.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_SINGORIXSENSOR.fields_by_name['joint_sensor_map'].message_type = _SINGORIXSENSOR_JOINTSENSORMAPENTRY
_SINGORIXSENSOR.fields_by_name['imu_sensor_map'].message_type = _SINGORIXSENSOR_IMUSENSORMAPENTRY
_SINGORIXSENSOR.fields_by_name['effort_sensor_map'].message_type = _SINGORIXSENSOR_EFFORTSENSORMAPENTRY
DESCRIPTOR.message_types_by_name['SingoriXSensor'] = _SINGORIXSENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SingoriXSensor = _reflection.GeneratedProtocolMessageType('SingoriXSensor', (_message.Message,), {

  'JointSensorMapEntry' : _reflection.GeneratedProtocolMessageType('JointSensorMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _SINGORIXSENSOR_JOINTSENSORMAPENTRY,
    '__module__' : 'galbot.singorix_proto.singorix_sensor_pb2'
    # @@protoc_insertion_point(class_scope:galbot.singorix_proto.SingoriXSensor.JointSensorMapEntry)
    })
  ,

  'ImuSensorMapEntry' : _reflection.GeneratedProtocolMessageType('ImuSensorMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _SINGORIXSENSOR_IMUSENSORMAPENTRY,
    '__module__' : 'galbot.singorix_proto.singorix_sensor_pb2'
    # @@protoc_insertion_point(class_scope:galbot.singorix_proto.SingoriXSensor.ImuSensorMapEntry)
    })
  ,

  'EffortSensorMapEntry' : _reflection.GeneratedProtocolMessageType('EffortSensorMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _SINGORIXSENSOR_EFFORTSENSORMAPENTRY,
    '__module__' : 'galbot.singorix_proto.singorix_sensor_pb2'
    # @@protoc_insertion_point(class_scope:galbot.singorix_proto.SingoriXSensor.EffortSensorMapEntry)
    })
  ,
  'DESCRIPTOR' : _SINGORIXSENSOR,
  '__module__' : 'galbot.singorix_proto.singorix_sensor_pb2'
  # @@protoc_insertion_point(class_scope:galbot.singorix_proto.SingoriXSensor)
  })
_sym_db.RegisterMessage(SingoriXSensor)
_sym_db.RegisterMessage(SingoriXSensor.JointSensorMapEntry)
_sym_db.RegisterMessage(SingoriXSensor.ImuSensorMapEntry)
_sym_db.RegisterMessage(SingoriXSensor.EffortSensorMapEntry)


_SINGORIXSENSOR_JOINTSENSORMAPENTRY._options = None
_SINGORIXSENSOR_IMUSENSORMAPENTRY._options = None
_SINGORIXSENSOR_EFFORTSENSORMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
