# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galbot/singorix_proto/singorix_error.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from galbot.core_proto import header_pb2 as galbot_dot_core__proto_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='galbot/singorix_proto/singorix_error.proto',
  package='galbot.singorix_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*galbot/singorix_proto/singorix_error.proto\x12\x15galbot.singorix_proto\x1a\x1egalbot/core_proto/header.proto\"6\n\x0b\x45rrorDetail\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\xd6\x01\n\rSingoriXError\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12\x45\n\terror_map\x18\x02 \x03(\x0b\x32\x32.galbot.singorix_proto.SingoriXError.ErrorMapEntry\x1aS\n\rErrorMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".galbot.singorix_proto.ErrorDetail:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[galbot_dot_core__proto_dot_header__pb2.DESCRIPTOR,])




_ERRORDETAIL = _descriptor.Descriptor(
  name='ErrorDetail',
  full_name='galbot.singorix_proto.ErrorDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='galbot.singorix_proto.ErrorDetail.error_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='galbot.singorix_proto.ErrorDetail.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=155,
)


_SINGORIXERROR_ERRORMAPENTRY = _descriptor.Descriptor(
  name='ErrorMapEntry',
  full_name='galbot.singorix_proto.SingoriXError.ErrorMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='galbot.singorix_proto.SingoriXError.ErrorMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='galbot.singorix_proto.SingoriXError.ErrorMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=372,
)

_SINGORIXERROR = _descriptor.Descriptor(
  name='SingoriXError',
  full_name='galbot.singorix_proto.SingoriXError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.singorix_proto.SingoriXError.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_map', full_name='galbot.singorix_proto.SingoriXError.error_map', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SINGORIXERROR_ERRORMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=372,
)

_SINGORIXERROR_ERRORMAPENTRY.fields_by_name['value'].message_type = _ERRORDETAIL
_SINGORIXERROR_ERRORMAPENTRY.containing_type = _SINGORIXERROR
_SINGORIXERROR.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_SINGORIXERROR.fields_by_name['error_map'].message_type = _SINGORIXERROR_ERRORMAPENTRY
DESCRIPTOR.message_types_by_name['ErrorDetail'] = _ERRORDETAIL
DESCRIPTOR.message_types_by_name['SingoriXError'] = _SINGORIXERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ErrorDetail = _reflection.GeneratedProtocolMessageType('ErrorDetail', (_message.Message,), {
  'DESCRIPTOR' : _ERRORDETAIL,
  '__module__' : 'galbot.singorix_proto.singorix_error_pb2'
  # @@protoc_insertion_point(class_scope:galbot.singorix_proto.ErrorDetail)
  })
_sym_db.RegisterMessage(ErrorDetail)

SingoriXError = _reflection.GeneratedProtocolMessageType('SingoriXError', (_message.Message,), {

  'ErrorMapEntry' : _reflection.GeneratedProtocolMessageType('ErrorMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _SINGORIXERROR_ERRORMAPENTRY,
    '__module__' : 'galbot.singorix_proto.singorix_error_pb2'
    # @@protoc_insertion_point(class_scope:galbot.singorix_proto.SingoriXError.ErrorMapEntry)
    })
  ,
  'DESCRIPTOR' : _SINGORIXERROR,
  '__module__' : 'galbot.singorix_proto.singorix_error_pb2'
  # @@protoc_insertion_point(class_scope:galbot.singorix_proto.SingoriXError)
  })
_sym_db.RegisterMessage(SingoriXError)
_sym_db.RegisterMessage(SingoriXError.ErrorMapEntry)


_SINGORIXERROR_ERRORMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
