# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galbot/sensor_proto/effort.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from galbot.core_proto import header_pb2 as galbot_dot_core__proto_dot_header__pb2
from galbot.core_proto import math_pb2 as galbot_dot_core__proto_dot_math__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='galbot/sensor_proto/effort.proto',
  package='galbot.sensor_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n galbot/sensor_proto/effort.proto\x12\x13galbot.sensor_proto\x1a\x1egalbot/core_proto/header.proto\x1a\x1cgalbot/core_proto/math.proto\"\x90\x01\n\x0c\x45\x66\x66ortSensor\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12)\n\x05\x66orce\x18\x02 \x01(\x0b\x32\x1a.galbot.core_proto.Vector3\x12*\n\x06torque\x18\x03 \x01(\x0b\x32\x1a.galbot.core_proto.Vector3b\x06proto3'
  ,
  dependencies=[galbot_dot_core__proto_dot_header__pb2.DESCRIPTOR,galbot_dot_core__proto_dot_math__pb2.DESCRIPTOR,])




_EFFORTSENSOR = _descriptor.Descriptor(
  name='EffortSensor',
  full_name='galbot.sensor_proto.EffortSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.sensor_proto.EffortSensor.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force', full_name='galbot.sensor_proto.EffortSensor.force', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='torque', full_name='galbot.sensor_proto.EffortSensor.torque', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=264,
)

_EFFORTSENSOR.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_EFFORTSENSOR.fields_by_name['force'].message_type = galbot_dot_core__proto_dot_math__pb2._VECTOR3
_EFFORTSENSOR.fields_by_name['torque'].message_type = galbot_dot_core__proto_dot_math__pb2._VECTOR3
DESCRIPTOR.message_types_by_name['EffortSensor'] = _EFFORTSENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EffortSensor = _reflection.GeneratedProtocolMessageType('EffortSensor', (_message.Message,), {
  'DESCRIPTOR' : _EFFORTSENSOR,
  '__module__' : 'galbot.sensor_proto.effort_pb2'
  # @@protoc_insertion_point(class_scope:galbot.sensor_proto.EffortSensor)
  })
_sym_db.RegisterMessage(EffortSensor)


# @@protoc_insertion_point(module_scope)
