# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galbot/sensor_proto/image.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from galbot.core_proto import header_pb2 as galbot_dot_core__proto_dot_header__pb2
from galbot.sensor_proto import roi_pb2 as galbot_dot_sensor__proto_dot_roi__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='galbot/sensor_proto/image.proto',
  package='galbot.sensor_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fgalbot/sensor_proto/image.proto\x12\x13galbot.sensor_proto\x1a\x1egalbot/core_proto/header.proto\x1a\x1dgalbot/sensor_proto/roi.proto\"\xaa\x01\n\x05Image\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\r\n\x05width\x18\x03 \x01(\r\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\t\x12\x14\n\x0cis_bigendian\x18\x05 \x01(\x05\x12\x0c\n\x04step\x18\x06 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x07 \x01(\x0c\x12\x13\n\x0b\x64\x65pth_scale\x18\x08 \x01(\r\"o\n\x0f\x43ompressedImage\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x13\n\x0b\x64\x65pth_scale\x18\x04 \x01(\r\"\xf8\x01\n\x0e\x44isparityImage\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12)\n\x05image\x18\x02 \x01(\x0b\x32\x1a.galbot.sensor_proto.Image\x12\t\n\x01\x66\x18\x03 \x01(\x02\x12\t\n\x01t\x18\x04 \x01(\x02\x12;\n\x0cvalid_window\x18\x05 \x01(\x0b\x32%.galbot.sensor_proto.RegionOfInterest\x12\x15\n\rmin_disparity\x18\x06 \x01(\x02\x12\x15\n\rmax_disparity\x18\x07 \x01(\x02\x12\x0f\n\x07\x64\x65lta_d\x18\x08 \x01(\x02\x62\x06proto3'
  ,
  dependencies=[galbot_dot_core__proto_dot_header__pb2.DESCRIPTOR,galbot_dot_sensor__proto_dot_roi__pb2.DESCRIPTOR,])




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='galbot.sensor_proto.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.sensor_proto.Image.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='galbot.sensor_proto.Image.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='galbot.sensor_proto.Image.width', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='galbot.sensor_proto.Image.encoding', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_bigendian', full_name='galbot.sensor_proto.Image.is_bigendian', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='step', full_name='galbot.sensor_proto.Image.step', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='galbot.sensor_proto.Image.data', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth_scale', full_name='galbot.sensor_proto.Image.depth_scale', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=290,
)


_COMPRESSEDIMAGE = _descriptor.Descriptor(
  name='CompressedImage',
  full_name='galbot.sensor_proto.CompressedImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.sensor_proto.CompressedImage.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='format', full_name='galbot.sensor_proto.CompressedImage.format', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='galbot.sensor_proto.CompressedImage.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth_scale', full_name='galbot.sensor_proto.CompressedImage.depth_scale', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=403,
)


_DISPARITYIMAGE = _descriptor.Descriptor(
  name='DisparityImage',
  full_name='galbot.sensor_proto.DisparityImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.sensor_proto.DisparityImage.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='galbot.sensor_proto.DisparityImage.image', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='f', full_name='galbot.sensor_proto.DisparityImage.f', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='t', full_name='galbot.sensor_proto.DisparityImage.t', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valid_window', full_name='galbot.sensor_proto.DisparityImage.valid_window', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_disparity', full_name='galbot.sensor_proto.DisparityImage.min_disparity', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_disparity', full_name='galbot.sensor_proto.DisparityImage.max_disparity', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delta_d', full_name='galbot.sensor_proto.DisparityImage.delta_d', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=654,
)

_IMAGE.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_COMPRESSEDIMAGE.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_DISPARITYIMAGE.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_DISPARITYIMAGE.fields_by_name['image'].message_type = _IMAGE
_DISPARITYIMAGE.fields_by_name['valid_window'].message_type = galbot_dot_sensor__proto_dot_roi__pb2._REGIONOFINTEREST
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['CompressedImage'] = _COMPRESSEDIMAGE
DESCRIPTOR.message_types_by_name['DisparityImage'] = _DISPARITYIMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'galbot.sensor_proto.image_pb2'
  # @@protoc_insertion_point(class_scope:galbot.sensor_proto.Image)
  })
_sym_db.RegisterMessage(Image)

CompressedImage = _reflection.GeneratedProtocolMessageType('CompressedImage', (_message.Message,), {
  'DESCRIPTOR' : _COMPRESSEDIMAGE,
  '__module__' : 'galbot.sensor_proto.image_pb2'
  # @@protoc_insertion_point(class_scope:galbot.sensor_proto.CompressedImage)
  })
_sym_db.RegisterMessage(CompressedImage)

DisparityImage = _reflection.GeneratedProtocolMessageType('DisparityImage', (_message.Message,), {
  'DESCRIPTOR' : _DISPARITYIMAGE,
  '__module__' : 'galbot.sensor_proto.image_pb2'
  # @@protoc_insertion_point(class_scope:galbot.sensor_proto.DisparityImage)
  })
_sym_db.RegisterMessage(DisparityImage)


# @@protoc_insertion_point(module_scope)
