# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galbot/sensor_proto/joint.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from galbot.core_proto import header_pb2 as galbot_dot_core__proto_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='galbot/sensor_proto/joint.proto',
  package='galbot.sensor_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fgalbot/sensor_proto/joint.proto\x12\x13galbot.sensor_proto\x1a\x1egalbot/core_proto/header.proto\"\x8b\x01\n\x0bJointSensor\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12\x0c\n\x04name\x18\x02 \x03(\t\x12\x10\n\x08position\x18\x03 \x03(\x01\x12\x10\n\x08velocity\x18\x04 \x03(\x01\x12\x0e\n\x06\x65\x66\x66ort\x18\x05 \x03(\x01\x12\x0f\n\x07\x63urrent\x18\x06 \x03(\x01\x62\x06proto3'
  ,
  dependencies=[galbot_dot_core__proto_dot_header__pb2.DESCRIPTOR,])




_JOINTSENSOR = _descriptor.Descriptor(
  name='JointSensor',
  full_name='galbot.sensor_proto.JointSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.sensor_proto.JointSensor.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='galbot.sensor_proto.JointSensor.name', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='galbot.sensor_proto.JointSensor.position', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='galbot.sensor_proto.JointSensor.velocity', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='effort', full_name='galbot.sensor_proto.JointSensor.effort', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current', full_name='galbot.sensor_proto.JointSensor.current', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=228,
)

_JOINTSENSOR.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
DESCRIPTOR.message_types_by_name['JointSensor'] = _JOINTSENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JointSensor = _reflection.GeneratedProtocolMessageType('JointSensor', (_message.Message,), {
  'DESCRIPTOR' : _JOINTSENSOR,
  '__module__' : 'galbot.sensor_proto.joint_pb2'
  # @@protoc_insertion_point(class_scope:galbot.sensor_proto.JointSensor)
  })
_sym_db.RegisterMessage(JointSensor)


# @@protoc_insertion_point(module_scope)
