# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galbot/sensor_proto/joy.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from galbot.core_proto import header_pb2 as galbot_dot_core__proto_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='galbot/sensor_proto/joy.proto',
  package='galbot.sensor_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dgalbot/sensor_proto/joy.proto\x12\x13galbot.sensor_proto\x1a\x1egalbot/core_proto/header.proto\"C\n\x06\x42utton\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12\x0e\n\x06status\x18\x02 \x01(\x05\"@\n\x04\x41xes\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12\r\n\x05value\x18\x02 \x01(\x01\"\x90\x01\n\x03Joy\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12\x30\n\x0b\x62utton_list\x18\x02 \x03(\x0b\x32\x1b.galbot.sensor_proto.Button\x12,\n\taxes_list\x18\x03 \x03(\x0b\x32\x19.galbot.sensor_proto.Axes\"\xd4\x01\n\x0bJoyFeedback\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12;\n\x04type\x18\x02 \x01(\x0e\x32-.galbot.sensor_proto.JoyFeedback.FeedbackType\x12\n\n\x02id\x18\x03 \x01(\r\x12\x11\n\tintensity\x18\x04 \x01(\x02\">\n\x0c\x46\x65\x65\x64\x62\x61\x63kType\x12\x0c\n\x08TYPE_LED\x10\x00\x12\x0f\n\x0bTYPE_RUMBLE\x10\x01\x12\x0f\n\x0bTYPE_BUZZER\x10\x02\"C\n\x10JoyFeedbackArray\x12/\n\x05\x61rray\x18\x01 \x03(\x0b\x32 .galbot.sensor_proto.JoyFeedbackb\x06proto3'
  ,
  dependencies=[galbot_dot_core__proto_dot_header__pb2.DESCRIPTOR,])



_JOYFEEDBACK_FEEDBACKTYPE = _descriptor.EnumDescriptor(
  name='FeedbackType',
  full_name='galbot.sensor_proto.JoyFeedback.FeedbackType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_LED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TYPE_RUMBLE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TYPE_BUZZER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=519,
  serialized_end=581,
)
_sym_db.RegisterEnumDescriptor(_JOYFEEDBACK_FEEDBACKTYPE)


_BUTTON = _descriptor.Descriptor(
  name='Button',
  full_name='galbot.sensor_proto.Button',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.sensor_proto.Button.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='galbot.sensor_proto.Button.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=153,
)


_AXES = _descriptor.Descriptor(
  name='Axes',
  full_name='galbot.sensor_proto.Axes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.sensor_proto.Axes.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='galbot.sensor_proto.Axes.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=219,
)


_JOY = _descriptor.Descriptor(
  name='Joy',
  full_name='galbot.sensor_proto.Joy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.sensor_proto.Joy.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='button_list', full_name='galbot.sensor_proto.Joy.button_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='axes_list', full_name='galbot.sensor_proto.Joy.axes_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=366,
)


_JOYFEEDBACK = _descriptor.Descriptor(
  name='JoyFeedback',
  full_name='galbot.sensor_proto.JoyFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.sensor_proto.JoyFeedback.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='galbot.sensor_proto.JoyFeedback.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='galbot.sensor_proto.JoyFeedback.id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intensity', full_name='galbot.sensor_proto.JoyFeedback.intensity', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JOYFEEDBACK_FEEDBACKTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=581,
)


_JOYFEEDBACKARRAY = _descriptor.Descriptor(
  name='JoyFeedbackArray',
  full_name='galbot.sensor_proto.JoyFeedbackArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='array', full_name='galbot.sensor_proto.JoyFeedbackArray.array', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=583,
  serialized_end=650,
)

_BUTTON.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_AXES.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_JOY.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_JOY.fields_by_name['button_list'].message_type = _BUTTON
_JOY.fields_by_name['axes_list'].message_type = _AXES
_JOYFEEDBACK.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_JOYFEEDBACK.fields_by_name['type'].enum_type = _JOYFEEDBACK_FEEDBACKTYPE
_JOYFEEDBACK_FEEDBACKTYPE.containing_type = _JOYFEEDBACK
_JOYFEEDBACKARRAY.fields_by_name['array'].message_type = _JOYFEEDBACK
DESCRIPTOR.message_types_by_name['Button'] = _BUTTON
DESCRIPTOR.message_types_by_name['Axes'] = _AXES
DESCRIPTOR.message_types_by_name['Joy'] = _JOY
DESCRIPTOR.message_types_by_name['JoyFeedback'] = _JOYFEEDBACK
DESCRIPTOR.message_types_by_name['JoyFeedbackArray'] = _JOYFEEDBACKARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Button = _reflection.GeneratedProtocolMessageType('Button', (_message.Message,), {
  'DESCRIPTOR' : _BUTTON,
  '__module__' : 'galbot.sensor_proto.joy_pb2'
  # @@protoc_insertion_point(class_scope:galbot.sensor_proto.Button)
  })
_sym_db.RegisterMessage(Button)

Axes = _reflection.GeneratedProtocolMessageType('Axes', (_message.Message,), {
  'DESCRIPTOR' : _AXES,
  '__module__' : 'galbot.sensor_proto.joy_pb2'
  # @@protoc_insertion_point(class_scope:galbot.sensor_proto.Axes)
  })
_sym_db.RegisterMessage(Axes)

Joy = _reflection.GeneratedProtocolMessageType('Joy', (_message.Message,), {
  'DESCRIPTOR' : _JOY,
  '__module__' : 'galbot.sensor_proto.joy_pb2'
  # @@protoc_insertion_point(class_scope:galbot.sensor_proto.Joy)
  })
_sym_db.RegisterMessage(Joy)

JoyFeedback = _reflection.GeneratedProtocolMessageType('JoyFeedback', (_message.Message,), {
  'DESCRIPTOR' : _JOYFEEDBACK,
  '__module__' : 'galbot.sensor_proto.joy_pb2'
  # @@protoc_insertion_point(class_scope:galbot.sensor_proto.JoyFeedback)
  })
_sym_db.RegisterMessage(JoyFeedback)

JoyFeedbackArray = _reflection.GeneratedProtocolMessageType('JoyFeedbackArray', (_message.Message,), {
  'DESCRIPTOR' : _JOYFEEDBACKARRAY,
  '__module__' : 'galbot.sensor_proto.joy_pb2'
  # @@protoc_insertion_point(class_scope:galbot.sensor_proto.JoyFeedbackArray)
  })
_sym_db.RegisterMessage(JoyFeedbackArray)


# @@protoc_insertion_point(module_scope)
