# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galbot/tf2_proto/tf2_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from galbot.spatial_proto import transform_pb2 as galbot_dot_spatial__proto_dot_transform__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='galbot/tf2_proto/tf2_message.proto',
  package='galbot.tf2_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"galbot/tf2_proto/tf2_message.proto\x12\x10galbot.tf2_proto\x1a$galbot/spatial_proto/transform.proto\"D\n\nTF2Message\x12\x36\n\ntransforms\x18\x01 \x03(\x0b\x32\".galbot.spatial_proto.TransformMsgb\x06proto3'
  ,
  dependencies=[galbot_dot_spatial__proto_dot_transform__pb2.DESCRIPTOR,])




_TF2MESSAGE = _descriptor.Descriptor(
  name='TF2Message',
  full_name='galbot.tf2_proto.TF2Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transforms', full_name='galbot.tf2_proto.TF2Message.transforms', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=162,
)

_TF2MESSAGE.fields_by_name['transforms'].message_type = galbot_dot_spatial__proto_dot_transform__pb2._TRANSFORMMSG
DESCRIPTOR.message_types_by_name['TF2Message'] = _TF2MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TF2Message = _reflection.GeneratedProtocolMessageType('TF2Message', (_message.Message,), {
  'DESCRIPTOR' : _TF2MESSAGE,
  '__module__' : 'galbot.tf2_proto.tf2_message_pb2'
  # @@protoc_insertion_point(class_scope:galbot.tf2_proto.TF2Message)
  })
_sym_db.RegisterMessage(TF2Message)


# @@protoc_insertion_point(module_scope)
