# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galbot/core_proto/time.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='galbot/core_proto/time.proto',
  package='galbot.core_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cgalbot/core_proto/time.proto\x12\x11galbot.core_proto\")\n\tTimestamp\x12\x0b\n\x03sec\x18\x01 \x01(\x03\x12\x0f\n\x07nanosec\x18\x02 \x01(\x07\"(\n\x08\x44uration\x12\x0b\n\x03sec\x18\x01 \x01(\x01\x12\x0f\n\x07nanosec\x18\x02 \x01(\x03\"\x7f\n\rTimeReference\x12.\n\x08time_sys\x18\x01 \x01(\x0b\x32\x1c.galbot.core_proto.Timestamp\x12.\n\x08time_ref\x18\x02 \x01(\x0b\x32\x1c.galbot.core_proto.Timestamp\x12\x0e\n\x06source\x18\x03 \x01(\tb\x06proto3'
)




_TIMESTAMP = _descriptor.Descriptor(
  name='Timestamp',
  full_name='galbot.core_proto.Timestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sec', full_name='galbot.core_proto.Timestamp.sec', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nanosec', full_name='galbot.core_proto.Timestamp.nanosec', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=92,
)


_DURATION = _descriptor.Descriptor(
  name='Duration',
  full_name='galbot.core_proto.Duration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sec', full_name='galbot.core_proto.Duration.sec', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nanosec', full_name='galbot.core_proto.Duration.nanosec', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=134,
)


_TIMEREFERENCE = _descriptor.Descriptor(
  name='TimeReference',
  full_name='galbot.core_proto.TimeReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_sys', full_name='galbot.core_proto.TimeReference.time_sys', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_ref', full_name='galbot.core_proto.TimeReference.time_ref', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='galbot.core_proto.TimeReference.source', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=263,
)

_TIMEREFERENCE.fields_by_name['time_sys'].message_type = _TIMESTAMP
_TIMEREFERENCE.fields_by_name['time_ref'].message_type = _TIMESTAMP
DESCRIPTOR.message_types_by_name['Timestamp'] = _TIMESTAMP
DESCRIPTOR.message_types_by_name['Duration'] = _DURATION
DESCRIPTOR.message_types_by_name['TimeReference'] = _TIMEREFERENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Timestamp = _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMP,
  '__module__' : 'galbot.core_proto.time_pb2'
  # @@protoc_insertion_point(class_scope:galbot.core_proto.Timestamp)
  })
_sym_db.RegisterMessage(Timestamp)

Duration = _reflection.GeneratedProtocolMessageType('Duration', (_message.Message,), {
  'DESCRIPTOR' : _DURATION,
  '__module__' : 'galbot.core_proto.time_pb2'
  # @@protoc_insertion_point(class_scope:galbot.core_proto.Duration)
  })
_sym_db.RegisterMessage(Duration)

TimeReference = _reflection.GeneratedProtocolMessageType('TimeReference', (_message.Message,), {
  'DESCRIPTOR' : _TIMEREFERENCE,
  '__module__' : 'galbot.core_proto.time_pb2'
  # @@protoc_insertion_point(class_scope:galbot.core_proto.TimeReference)
  })
_sym_db.RegisterMessage(TimeReference)


# @@protoc_insertion_point(module_scope)
