# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galbot/spatial_proto/frame.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from galbot.core_proto import header_pb2 as galbot_dot_core__proto_dot_header__pb2
from galbot.spatial_proto import pose_pb2 as galbot_dot_spatial__proto_dot_pose__pb2
from galbot.spatial_proto import twist_pb2 as galbot_dot_spatial__proto_dot_twist__pb2
from galbot.spatial_proto import wrench_pb2 as galbot_dot_spatial__proto_dot_wrench__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='galbot/spatial_proto/frame.proto',
  package='galbot.spatial_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n galbot/spatial_proto/frame.proto\x12\x14galbot.spatial_proto\x1a\x1egalbot/core_proto/header.proto\x1a\x1fgalbot/spatial_proto/pose.proto\x1a galbot/spatial_proto/twist.proto\x1a!galbot/spatial_proto/wrench.proto\"\x8b\x01\n\x05\x46rame\x12(\n\x04pose\x18\x01 \x01(\x0b\x32\x1a.galbot.spatial_proto.Pose\x12*\n\x05twist\x18\x02 \x01(\x0b\x32\x1b.galbot.spatial_proto.Twist\x12,\n\x06wrench\x18\x03 \x01(\x0b\x32\x1c.galbot.spatial_proto.Wrench\"a\n\x08\x46rameMsg\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12*\n\x05\x66rame\x18\x02 \x01(\x0b\x32\x1b.galbot.spatial_proto.Frame\"\x83\x02\n\nFrameTriad\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12\x15\n\rbody_frame_id\x18\x02 \x01(\t\x12\x1a\n\x12reference_frame_id\x18\x03 \x01(\t\x12/\n\x08pose_msg\x18\x04 \x01(\x0b\x32\x1d.galbot.spatial_proto.PoseMsg\x12\x31\n\ttwist_msg\x18\x05 \x01(\x0b\x32\x1e.galbot.spatial_proto.TwistMsg\x12\x33\n\nwrench_msg\x18\x06 \x01(\x0b\x32\x1f.galbot.spatial_proto.WrenchMsgb\x06proto3'
  ,
  dependencies=[galbot_dot_core__proto_dot_header__pb2.DESCRIPTOR,galbot_dot_spatial__proto_dot_pose__pb2.DESCRIPTOR,galbot_dot_spatial__proto_dot_twist__pb2.DESCRIPTOR,galbot_dot_spatial__proto_dot_wrench__pb2.DESCRIPTOR,])




_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='galbot.spatial_proto.Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='galbot.spatial_proto.Frame.pose', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='twist', full_name='galbot.spatial_proto.Frame.twist', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wrench', full_name='galbot.spatial_proto.Frame.wrench', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=332,
)


_FRAMEMSG = _descriptor.Descriptor(
  name='FrameMsg',
  full_name='galbot.spatial_proto.FrameMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.spatial_proto.FrameMsg.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame', full_name='galbot.spatial_proto.FrameMsg.frame', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=431,
)


_FRAMETRIAD = _descriptor.Descriptor(
  name='FrameTriad',
  full_name='galbot.spatial_proto.FrameTriad',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.spatial_proto.FrameTriad.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body_frame_id', full_name='galbot.spatial_proto.FrameTriad.body_frame_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reference_frame_id', full_name='galbot.spatial_proto.FrameTriad.reference_frame_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pose_msg', full_name='galbot.spatial_proto.FrameTriad.pose_msg', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='twist_msg', full_name='galbot.spatial_proto.FrameTriad.twist_msg', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wrench_msg', full_name='galbot.spatial_proto.FrameTriad.wrench_msg', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=693,
)

_FRAME.fields_by_name['pose'].message_type = galbot_dot_spatial__proto_dot_pose__pb2._POSE
_FRAME.fields_by_name['twist'].message_type = galbot_dot_spatial__proto_dot_twist__pb2._TWIST
_FRAME.fields_by_name['wrench'].message_type = galbot_dot_spatial__proto_dot_wrench__pb2._WRENCH
_FRAMEMSG.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_FRAMEMSG.fields_by_name['frame'].message_type = _FRAME
_FRAMETRIAD.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_FRAMETRIAD.fields_by_name['pose_msg'].message_type = galbot_dot_spatial__proto_dot_pose__pb2._POSEMSG
_FRAMETRIAD.fields_by_name['twist_msg'].message_type = galbot_dot_spatial__proto_dot_twist__pb2._TWISTMSG
_FRAMETRIAD.fields_by_name['wrench_msg'].message_type = galbot_dot_spatial__proto_dot_wrench__pb2._WRENCHMSG
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
DESCRIPTOR.message_types_by_name['FrameMsg'] = _FRAMEMSG
DESCRIPTOR.message_types_by_name['FrameTriad'] = _FRAMETRIAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), {
  'DESCRIPTOR' : _FRAME,
  '__module__' : 'galbot.spatial_proto.frame_pb2'
  # @@protoc_insertion_point(class_scope:galbot.spatial_proto.Frame)
  })
_sym_db.RegisterMessage(Frame)

FrameMsg = _reflection.GeneratedProtocolMessageType('FrameMsg', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEMSG,
  '__module__' : 'galbot.spatial_proto.frame_pb2'
  # @@protoc_insertion_point(class_scope:galbot.spatial_proto.FrameMsg)
  })
_sym_db.RegisterMessage(FrameMsg)

FrameTriad = _reflection.GeneratedProtocolMessageType('FrameTriad', (_message.Message,), {
  'DESCRIPTOR' : _FRAMETRIAD,
  '__module__' : 'galbot.spatial_proto.frame_pb2'
  # @@protoc_insertion_point(class_scope:galbot.spatial_proto.FrameTriad)
  })
_sym_db.RegisterMessage(FrameTriad)


# @@protoc_insertion_point(module_scope)
