# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galbot/spatial_proto/pose.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from galbot.core_proto import header_pb2 as galbot_dot_core__proto_dot_header__pb2
from galbot.core_proto import math_pb2 as galbot_dot_core__proto_dot_math__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='galbot/spatial_proto/pose.proto',
  package='galbot.spatial_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fgalbot/spatial_proto/pose.proto\x12\x14galbot.spatial_proto\x1a\x1egalbot/core_proto/header.proto\x1a\x1cgalbot/core_proto/math.proto\"f\n\x04Pose\x12*\n\x08position\x18\x01 \x01(\x0b\x32\x18.galbot.core_proto.Point\x12\x32\n\x0borientation\x18\x02 \x01(\x0b\x32\x1d.galbot.core_proto.Quaternion\"-\n\x06Pose2D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\r\n\x05theta\x18\x03 \x01(\x01\"a\n\tPoseArray\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12)\n\x05poses\x18\x02 \x03(\x0b\x32\x1a.galbot.spatial_proto.Pose\"\x91\x01\n\x07PoseMsg\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12(\n\x04pose\x18\x02 \x01(\x0b\x32\x1a.galbot.spatial_proto.Pose\x12\x31\n\ncovariance\x18\x03 \x01(\x0b\x32\x1d.galbot.core_proto.Covariance\"g\n\x0cPoseMsgArray\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12,\n\x05poses\x18\x02 \x03(\x0b\x32\x1d.galbot.spatial_proto.PoseMsgb\x06proto3'
  ,
  dependencies=[galbot_dot_core__proto_dot_header__pb2.DESCRIPTOR,galbot_dot_core__proto_dot_math__pb2.DESCRIPTOR,])




_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='galbot.spatial_proto.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='galbot.spatial_proto.Pose.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='galbot.spatial_proto.Pose.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=221,
)


_POSE2D = _descriptor.Descriptor(
  name='Pose2D',
  full_name='galbot.spatial_proto.Pose2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='galbot.spatial_proto.Pose2D.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='galbot.spatial_proto.Pose2D.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='theta', full_name='galbot.spatial_proto.Pose2D.theta', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=268,
)


_POSEARRAY = _descriptor.Descriptor(
  name='PoseArray',
  full_name='galbot.spatial_proto.PoseArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.spatial_proto.PoseArray.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='poses', full_name='galbot.spatial_proto.PoseArray.poses', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=367,
)


_POSEMSG = _descriptor.Descriptor(
  name='PoseMsg',
  full_name='galbot.spatial_proto.PoseMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.spatial_proto.PoseMsg.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pose', full_name='galbot.spatial_proto.PoseMsg.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='galbot.spatial_proto.PoseMsg.covariance', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=515,
)


_POSEMSGARRAY = _descriptor.Descriptor(
  name='PoseMsgArray',
  full_name='galbot.spatial_proto.PoseMsgArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.spatial_proto.PoseMsgArray.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='poses', full_name='galbot.spatial_proto.PoseMsgArray.poses', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=620,
)

_POSE.fields_by_name['position'].message_type = galbot_dot_core__proto_dot_math__pb2._POINT
_POSE.fields_by_name['orientation'].message_type = galbot_dot_core__proto_dot_math__pb2._QUATERNION
_POSEARRAY.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_POSEARRAY.fields_by_name['poses'].message_type = _POSE
_POSEMSG.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_POSEMSG.fields_by_name['pose'].message_type = _POSE
_POSEMSG.fields_by_name['covariance'].message_type = galbot_dot_core__proto_dot_math__pb2._COVARIANCE
_POSEMSGARRAY.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_POSEMSGARRAY.fields_by_name['poses'].message_type = _POSEMSG
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
DESCRIPTOR.message_types_by_name['Pose2D'] = _POSE2D
DESCRIPTOR.message_types_by_name['PoseArray'] = _POSEARRAY
DESCRIPTOR.message_types_by_name['PoseMsg'] = _POSEMSG
DESCRIPTOR.message_types_by_name['PoseMsgArray'] = _POSEMSGARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), {
  'DESCRIPTOR' : _POSE,
  '__module__' : 'galbot.spatial_proto.pose_pb2'
  # @@protoc_insertion_point(class_scope:galbot.spatial_proto.Pose)
  })
_sym_db.RegisterMessage(Pose)

Pose2D = _reflection.GeneratedProtocolMessageType('Pose2D', (_message.Message,), {
  'DESCRIPTOR' : _POSE2D,
  '__module__' : 'galbot.spatial_proto.pose_pb2'
  # @@protoc_insertion_point(class_scope:galbot.spatial_proto.Pose2D)
  })
_sym_db.RegisterMessage(Pose2D)

PoseArray = _reflection.GeneratedProtocolMessageType('PoseArray', (_message.Message,), {
  'DESCRIPTOR' : _POSEARRAY,
  '__module__' : 'galbot.spatial_proto.pose_pb2'
  # @@protoc_insertion_point(class_scope:galbot.spatial_proto.PoseArray)
  })
_sym_db.RegisterMessage(PoseArray)

PoseMsg = _reflection.GeneratedProtocolMessageType('PoseMsg', (_message.Message,), {
  'DESCRIPTOR' : _POSEMSG,
  '__module__' : 'galbot.spatial_proto.pose_pb2'
  # @@protoc_insertion_point(class_scope:galbot.spatial_proto.PoseMsg)
  })
_sym_db.RegisterMessage(PoseMsg)

PoseMsgArray = _reflection.GeneratedProtocolMessageType('PoseMsgArray', (_message.Message,), {
  'DESCRIPTOR' : _POSEMSGARRAY,
  '__module__' : 'galbot.spatial_proto.pose_pb2'
  # @@protoc_insertion_point(class_scope:galbot.spatial_proto.PoseMsgArray)
  })
_sym_db.RegisterMessage(PoseMsgArray)


# @@protoc_insertion_point(module_scope)
