# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galbot/spatial_proto/transform.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from galbot.core_proto import header_pb2 as galbot_dot_core__proto_dot_header__pb2
from galbot.core_proto import math_pb2 as galbot_dot_core__proto_dot_math__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='galbot/spatial_proto/transform.proto',
  package='galbot.spatial_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$galbot/spatial_proto/transform.proto\x12\x14galbot.spatial_proto\x1a\x1egalbot/core_proto/header.proto\x1a\x1cgalbot/core_proto/math.proto\"m\n\tTransform\x12/\n\x0btranslation\x18\x01 \x01(\x0b\x32\x1a.galbot.core_proto.Vector3\x12/\n\x08rotation\x18\x02 \x01(\x0b\x32\x1d.galbot.core_proto.Quaternion\"\x85\x01\n\x0cTransformMsg\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12\x16\n\x0e\x63hild_frame_id\x18\x02 \x01(\t\x12\x32\n\ttransform\x18\x03 \x01(\x0b\x32\x1f.galbot.spatial_proto.Transformb\x06proto3'
  ,
  dependencies=[galbot_dot_core__proto_dot_header__pb2.DESCRIPTOR,galbot_dot_core__proto_dot_math__pb2.DESCRIPTOR,])




_TRANSFORM = _descriptor.Descriptor(
  name='Transform',
  full_name='galbot.spatial_proto.Transform',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='translation', full_name='galbot.spatial_proto.Transform.translation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='galbot.spatial_proto.Transform.rotation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=233,
)


_TRANSFORMMSG = _descriptor.Descriptor(
  name='TransformMsg',
  full_name='galbot.spatial_proto.TransformMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.spatial_proto.TransformMsg.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='child_frame_id', full_name='galbot.spatial_proto.TransformMsg.child_frame_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transform', full_name='galbot.spatial_proto.TransformMsg.transform', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=369,
)

_TRANSFORM.fields_by_name['translation'].message_type = galbot_dot_core__proto_dot_math__pb2._VECTOR3
_TRANSFORM.fields_by_name['rotation'].message_type = galbot_dot_core__proto_dot_math__pb2._QUATERNION
_TRANSFORMMSG.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_TRANSFORMMSG.fields_by_name['transform'].message_type = _TRANSFORM
DESCRIPTOR.message_types_by_name['Transform'] = _TRANSFORM
DESCRIPTOR.message_types_by_name['TransformMsg'] = _TRANSFORMMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Transform = _reflection.GeneratedProtocolMessageType('Transform', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFORM,
  '__module__' : 'galbot.spatial_proto.transform_pb2'
  # @@protoc_insertion_point(class_scope:galbot.spatial_proto.Transform)
  })
_sym_db.RegisterMessage(Transform)

TransformMsg = _reflection.GeneratedProtocolMessageType('TransformMsg', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFORMMSG,
  '__module__' : 'galbot.spatial_proto.transform_pb2'
  # @@protoc_insertion_point(class_scope:galbot.spatial_proto.TransformMsg)
  })
_sym_db.RegisterMessage(TransformMsg)


# @@protoc_insertion_point(module_scope)
