# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galbot/spatial_proto/twist.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from galbot.core_proto import header_pb2 as galbot_dot_core__proto_dot_header__pb2
from galbot.core_proto import math_pb2 as galbot_dot_core__proto_dot_math__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='galbot/spatial_proto/twist.proto',
  package='galbot.spatial_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n galbot/spatial_proto/twist.proto\x12\x14galbot.spatial_proto\x1a\x1egalbot/core_proto/header.proto\x1a\x1cgalbot/core_proto/math.proto\"`\n\x05Twist\x12*\n\x06linear\x18\x01 \x01(\x0b\x32\x1a.galbot.core_proto.Vector3\x12+\n\x07\x61ngular\x18\x02 \x01(\x0b\x32\x1a.galbot.core_proto.Vector3\"\x94\x01\n\x08TwistMsg\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12*\n\x05twist\x18\x02 \x01(\x0b\x32\x1b.galbot.spatial_proto.Twist\x12\x31\n\ncovariance\x18\x03 \x01(\x0b\x32\x1d.galbot.core_proto.Covariance\"\x9a\x01\n\x0bVelocityMsg\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12\x15\n\rbody_frame_id\x18\x02 \x01(\t\x12\x1a\n\x12reference_frame_id\x18\x03 \x01(\t\x12-\n\x08velocity\x18\x04 \x01(\x0b\x32\x1b.galbot.spatial_proto.Twistb\x06proto3'
  ,
  dependencies=[galbot_dot_core__proto_dot_header__pb2.DESCRIPTOR,galbot_dot_core__proto_dot_math__pb2.DESCRIPTOR,])




_TWIST = _descriptor.Descriptor(
  name='Twist',
  full_name='galbot.spatial_proto.Twist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear', full_name='galbot.spatial_proto.Twist.linear', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angular', full_name='galbot.spatial_proto.Twist.angular', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=216,
)


_TWISTMSG = _descriptor.Descriptor(
  name='TwistMsg',
  full_name='galbot.spatial_proto.TwistMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.spatial_proto.TwistMsg.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='twist', full_name='galbot.spatial_proto.TwistMsg.twist', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='galbot.spatial_proto.TwistMsg.covariance', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=367,
)


_VELOCITYMSG = _descriptor.Descriptor(
  name='VelocityMsg',
  full_name='galbot.spatial_proto.VelocityMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.spatial_proto.VelocityMsg.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body_frame_id', full_name='galbot.spatial_proto.VelocityMsg.body_frame_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reference_frame_id', full_name='galbot.spatial_proto.VelocityMsg.reference_frame_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='galbot.spatial_proto.VelocityMsg.velocity', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=524,
)

_TWIST.fields_by_name['linear'].message_type = galbot_dot_core__proto_dot_math__pb2._VECTOR3
_TWIST.fields_by_name['angular'].message_type = galbot_dot_core__proto_dot_math__pb2._VECTOR3
_TWISTMSG.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_TWISTMSG.fields_by_name['twist'].message_type = _TWIST
_TWISTMSG.fields_by_name['covariance'].message_type = galbot_dot_core__proto_dot_math__pb2._COVARIANCE
_VELOCITYMSG.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_VELOCITYMSG.fields_by_name['velocity'].message_type = _TWIST
DESCRIPTOR.message_types_by_name['Twist'] = _TWIST
DESCRIPTOR.message_types_by_name['TwistMsg'] = _TWISTMSG
DESCRIPTOR.message_types_by_name['VelocityMsg'] = _VELOCITYMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Twist = _reflection.GeneratedProtocolMessageType('Twist', (_message.Message,), {
  'DESCRIPTOR' : _TWIST,
  '__module__' : 'galbot.spatial_proto.twist_pb2'
  # @@protoc_insertion_point(class_scope:galbot.spatial_proto.Twist)
  })
_sym_db.RegisterMessage(Twist)

TwistMsg = _reflection.GeneratedProtocolMessageType('TwistMsg', (_message.Message,), {
  'DESCRIPTOR' : _TWISTMSG,
  '__module__' : 'galbot.spatial_proto.twist_pb2'
  # @@protoc_insertion_point(class_scope:galbot.spatial_proto.TwistMsg)
  })
_sym_db.RegisterMessage(TwistMsg)

VelocityMsg = _reflection.GeneratedProtocolMessageType('VelocityMsg', (_message.Message,), {
  'DESCRIPTOR' : _VELOCITYMSG,
  '__module__' : 'galbot.spatial_proto.twist_pb2'
  # @@protoc_insertion_point(class_scope:galbot.spatial_proto.VelocityMsg)
  })
_sym_db.RegisterMessage(VelocityMsg)


# @@protoc_insertion_point(module_scope)
