# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galbot/spatial_proto/wrench.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from galbot.core_proto import header_pb2 as galbot_dot_core__proto_dot_header__pb2
from galbot.core_proto import math_pb2 as galbot_dot_core__proto_dot_math__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='galbot/spatial_proto/wrench.proto',
  package='galbot.spatial_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!galbot/spatial_proto/wrench.proto\x12\x14galbot.spatial_proto\x1a\x1egalbot/core_proto/header.proto\x1a\x1cgalbot/core_proto/math.proto\"_\n\x06Wrench\x12)\n\x05\x66orce\x18\x01 \x01(\x0b\x32\x1a.galbot.core_proto.Vector3\x12*\n\x06torque\x18\x02 \x01(\x0b\x32\x1a.galbot.core_proto.Vector3\"\x97\x01\n\tWrenchMsg\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12,\n\x06wrench\x18\x02 \x01(\x0b\x32\x1c.galbot.spatial_proto.Wrench\x12\x31\n\ncovariance\x18\x03 \x01(\x0b\x32\x1d.galbot.core_proto.Covarianceb\x06proto3'
  ,
  dependencies=[galbot_dot_core__proto_dot_header__pb2.DESCRIPTOR,galbot_dot_core__proto_dot_math__pb2.DESCRIPTOR,])




_WRENCH = _descriptor.Descriptor(
  name='Wrench',
  full_name='galbot.spatial_proto.Wrench',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='force', full_name='galbot.spatial_proto.Wrench.force', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='torque', full_name='galbot.spatial_proto.Wrench.torque', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=216,
)


_WRENCHMSG = _descriptor.Descriptor(
  name='WrenchMsg',
  full_name='galbot.spatial_proto.WrenchMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.spatial_proto.WrenchMsg.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wrench', full_name='galbot.spatial_proto.WrenchMsg.wrench', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='galbot.spatial_proto.WrenchMsg.covariance', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=370,
)

_WRENCH.fields_by_name['force'].message_type = galbot_dot_core__proto_dot_math__pb2._VECTOR3
_WRENCH.fields_by_name['torque'].message_type = galbot_dot_core__proto_dot_math__pb2._VECTOR3
_WRENCHMSG.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_WRENCHMSG.fields_by_name['wrench'].message_type = _WRENCH
_WRENCHMSG.fields_by_name['covariance'].message_type = galbot_dot_core__proto_dot_math__pb2._COVARIANCE
DESCRIPTOR.message_types_by_name['Wrench'] = _WRENCH
DESCRIPTOR.message_types_by_name['WrenchMsg'] = _WRENCHMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Wrench = _reflection.GeneratedProtocolMessageType('Wrench', (_message.Message,), {
  'DESCRIPTOR' : _WRENCH,
  '__module__' : 'galbot.spatial_proto.wrench_pb2'
  # @@protoc_insertion_point(class_scope:galbot.spatial_proto.Wrench)
  })
_sym_db.RegisterMessage(Wrench)

WrenchMsg = _reflection.GeneratedProtocolMessageType('WrenchMsg', (_message.Message,), {
  'DESCRIPTOR' : _WRENCHMSG,
  '__module__' : 'galbot.spatial_proto.wrench_pb2'
  # @@protoc_insertion_point(class_scope:galbot.spatial_proto.WrenchMsg)
  })
_sym_db.RegisterMessage(WrenchMsg)


# @@protoc_insertion_point(module_scope)
